version: "3.9" 

 

services: 

 

  postgres: 

    image: postgres:17-alpine 

    container_name: tasker-postgres 

    environment: 

      POSTGRES_DB:       taskerdb 

      POSTGRES_USER:     tasker 

      POSTGRES_PASSWORD: tasker 

    ports: 

      - "5432:5432" 

    volumes: 

      - postgres_data:/var/lib/postgresql/data 

      - ./docker/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro 

    healthcheck: 

      test: ["CMD", "pg_isready", "-U", "tasker", "-d", "taskerdb"] 

      interval: 10s 

      timeout: 5s 

      retries: 5 

 

  mongo: 

    image: mongo:8.0 

    container_name: tasker-mongo 

    ports: 

      - "27017:27017" 

    volumes: 

      - mongo_data:/data/db 

    healthcheck: 

      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"] 

      interval: 10s 

      timeout: 5s 

      retries: 5 

 

  app: 

    build: 

      context: . 

      dockerfile: Dockerfile 

    container_name: tasker-app 

    depends_on: 

      postgres: 

        condition: service_healthy 

      mongo: 

        condition: service_healthy 

    environment: 

      SPRING_PROFILES_ACTIVE: docker 

      POSTGRES_HOST:          postgres 

      POSTGRES_DB:            taskerdb 

      POSTGRES_USER:          tasker 

      POSTGRES_PASSWORD:      tasker 

      MONGO_HOST:             mongo 

      MONGO_DB:               tasker_audit 

      JWT_SECRET:             local-prod-secret-32-characters-ok 

    ports: 

      - "8080:8080" 

    healthcheck: 

      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"] 

      interval: 15s 

      timeout: 5s 

      retries: 5 

 

volumes: 

  postgres_data: 

  mongo_data: 