spring:
  application:
    name: tasker
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: admin
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update